describe("settings", function()
    it("has the correct defaults", function()
        local settings = require("portal.settings")
        assert.equals("warn", settings.log_level)

        assert.is_nil(settings.query)
        assert.not_nil(settings.filter)
        assert.equals(100, settings.lookback)
        assert.are.same({ "j", "k", "h", "l" }, settings.labels)

        local esc = vim.api.nvim_replace_termcodes("<esc>", true, false, true)
        assert.equals(esc, settings.escape[1])

        assert.equals("cursor", settings.window_options.relative)
        assert.equals(80, settings.window_options.width)
        assert.equals(3, settings.window_options.height)
        assert.equals(2, settings.window_options.col)
        assert.equals(false, settings.window_options.focusable)
        assert.equals("single", settings.window_options.border)
        assert.equals(true, settings.window_options.noautocmd)
    end)
end)
